export const LOAD_DEVICES_SUCCESS = 'LOAD_DEVICES_SUCCESS';
export const SAVE_NEW_DEVICE = 'SAVE_NEW_DEVICE';
export const GET_SENSOR = 'GET_SENSOR';
export const GET_NUMBER_OF_RUNNING_SENSORS = 'GET_NUMBER_OF_RUNNING_SENSORS';
